<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <!-- TargetFramework is defined in Directory.Build.props for consistency -->
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

  </PropertyGroup>
  <ItemGroup>
    <SupportedPlatform Include="browser" />
    <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.0" />
  </ItemGroup>
</Project>