<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

  </PropertyGroup>
  <ItemGroup>
    <SupportedPlatform Include="browser" />
    <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.0-preview.2.25164.1" />
  </ItemGroup>
</Project>